#ifndef PARAMS_H
#define PARAMS_H

#define BASIC_CHEAP_AND_QUICK
#define MAX_NUM_NODES 31
#define MAX_NUM_SIGNATURES 16
#define MAX_NUM_TRANSACTIONS 1000
#define PAYLOAD_SIZE 0

#define HTBFT 
#endif
